//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_Assignment.MyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyServiceReference.MyServiceSoap")]
    public interface MyServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WAPP_Assignment.MyServiceReference.HelloWorldResponse HelloWorld(WAPP_Assignment.MyServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WAPP_Assignment.MyServiceReference.HelloWorldResponse> HelloWorldAsync(WAPP_Assignment.MyServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name table from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUsernameDuplicate", ReplyAction="*")]
        WAPP_Assignment.MyServiceReference.IsUsernameDuplicateResponse IsUsernameDuplicate(WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUsernameDuplicate", ReplyAction="*")]
        System.Threading.Tasks.Task<WAPP_Assignment.MyServiceReference.IsUsernameDuplicateResponse> IsUsernameDuplicateAsync(WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WAPP_Assignment.MyServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WAPP_Assignment.MyServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAPP_Assignment.MyServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WAPP_Assignment.MyServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUsernameDuplicateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUsernameDuplicate", Namespace="http://tempuri.org/", Order=0)]
        public WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequestBody Body;
        
        public IsUsernameDuplicateRequest() {
        }
        
        public IsUsernameDuplicateRequest(WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsUsernameDuplicateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string table;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        public IsUsernameDuplicateRequestBody() {
        }
        
        public IsUsernameDuplicateRequestBody(string table, string username) {
            this.table = table;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUsernameDuplicateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUsernameDuplicateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAPP_Assignment.MyServiceReference.IsUsernameDuplicateResponseBody Body;
        
        public IsUsernameDuplicateResponse() {
        }
        
        public IsUsernameDuplicateResponse(WAPP_Assignment.MyServiceReference.IsUsernameDuplicateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsUsernameDuplicateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsUsernameDuplicateResult;
        
        public IsUsernameDuplicateResponseBody() {
        }
        
        public IsUsernameDuplicateResponseBody(bool IsUsernameDuplicateResult) {
            this.IsUsernameDuplicateResult = IsUsernameDuplicateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServiceSoapChannel : WAPP_Assignment.MyServiceReference.MyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceSoapClient : System.ServiceModel.ClientBase<WAPP_Assignment.MyServiceReference.MyServiceSoap>, WAPP_Assignment.MyServiceReference.MyServiceSoap {
        
        public MyServiceSoapClient() {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAPP_Assignment.MyServiceReference.HelloWorldResponse WAPP_Assignment.MyServiceReference.MyServiceSoap.HelloWorld(WAPP_Assignment.MyServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WAPP_Assignment.MyServiceReference.HelloWorldRequest inValue = new WAPP_Assignment.MyServiceReference.HelloWorldRequest();
            inValue.Body = new WAPP_Assignment.MyServiceReference.HelloWorldRequestBody();
            WAPP_Assignment.MyServiceReference.HelloWorldResponse retVal = ((WAPP_Assignment.MyServiceReference.MyServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAPP_Assignment.MyServiceReference.HelloWorldResponse> WAPP_Assignment.MyServiceReference.MyServiceSoap.HelloWorldAsync(WAPP_Assignment.MyServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAPP_Assignment.MyServiceReference.HelloWorldResponse> HelloWorldAsync() {
            WAPP_Assignment.MyServiceReference.HelloWorldRequest inValue = new WAPP_Assignment.MyServiceReference.HelloWorldRequest();
            inValue.Body = new WAPP_Assignment.MyServiceReference.HelloWorldRequestBody();
            return ((WAPP_Assignment.MyServiceReference.MyServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAPP_Assignment.MyServiceReference.IsUsernameDuplicateResponse WAPP_Assignment.MyServiceReference.MyServiceSoap.IsUsernameDuplicate(WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequest request) {
            return base.Channel.IsUsernameDuplicate(request);
        }
        
        public bool IsUsernameDuplicate(string table, string username) {
            WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequest inValue = new WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequest();
            inValue.Body = new WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequestBody();
            inValue.Body.table = table;
            inValue.Body.username = username;
            WAPP_Assignment.MyServiceReference.IsUsernameDuplicateResponse retVal = ((WAPP_Assignment.MyServiceReference.MyServiceSoap)(this)).IsUsernameDuplicate(inValue);
            return retVal.Body.IsUsernameDuplicateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAPP_Assignment.MyServiceReference.IsUsernameDuplicateResponse> WAPP_Assignment.MyServiceReference.MyServiceSoap.IsUsernameDuplicateAsync(WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequest request) {
            return base.Channel.IsUsernameDuplicateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAPP_Assignment.MyServiceReference.IsUsernameDuplicateResponse> IsUsernameDuplicateAsync(string table, string username) {
            WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequest inValue = new WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequest();
            inValue.Body = new WAPP_Assignment.MyServiceReference.IsUsernameDuplicateRequestBody();
            inValue.Body.table = table;
            inValue.Body.username = username;
            return ((WAPP_Assignment.MyServiceReference.MyServiceSoap)(this)).IsUsernameDuplicateAsync(inValue);
        }
    }
}
